baseURL = "https://yyym2017.github.io/MyBlogSite/"
title = "Less的博客空间"
languageCode = "zh_cn"
DefaultContentLanguage = "zh_cn"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = 'HugoTeX'

[pagination]
  pagerSize = 10

[Params.author]
  name = "Less"
  abstract = """
 choose !!!
  """

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "paraiso-dark"

[Params]
  darkmode = true
